<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260414061535 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE ingredient ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ingredient ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE meal ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE meal ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_meal_trip RENAME TO IDX_9EF68E9CA5BC2E0E');
        $this->addSql('ALTER INDEX idx_meal_recipe_meal RENAME TO IDX_B5820C3E639666D6');
        $this->addSql('ALTER INDEX idx_meal_recipe_recipe RENAME TO IDX_B5820C3E59D8A214');
        $this->addSql('ALTER INDEX idx_meal_participant_meal RENAME TO IDX_DA656D99639666D6');
        $this->addSql('ALTER INDEX idx_meal_participant_participant RENAME TO IDX_DA656D999D1C3019');
        $this->addSql('ALTER TABLE participant ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE participant ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE participant ALTER nights_present TYPE JSON');
        $this->addSql('ALTER INDEX idx_participant_trip RENAME TO IDX_D79F6B11A5BC2E0E');
        $this->addSql('ALTER TABLE recipe ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE recipe ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE recipe_ingredient ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE recipe_ingredient ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE recipe_ingredient ALTER quantity TYPE DOUBLE PRECISION');
        $this->addSql('ALTER INDEX idx_recipe_ingredient_recipe RENAME TO IDX_22D1FE1359D8A214');
        $this->addSql('ALTER INDEX idx_recipe_ingredient_ingredient RENAME TO IDX_22D1FE13933FE08C');
        $this->addSql('ALTER TABLE trip ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE trip ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE trip ALTER total_budget TYPE DOUBLE PRECISION');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE ingredient ALTER id SET DEFAULT nextval(\'ingredient_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE ingredient ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE meal ALTER id SET DEFAULT nextval(\'meal_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE meal ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX idx_9ef68e9ca5bc2e0e RENAME TO idx_meal_trip');
        $this->addSql('ALTER INDEX idx_da656d99639666d6 RENAME TO idx_meal_participant_meal');
        $this->addSql('ALTER INDEX idx_da656d999d1c3019 RENAME TO idx_meal_participant_participant');
        $this->addSql('ALTER INDEX idx_b5820c3e59d8a214 RENAME TO idx_meal_recipe_recipe');
        $this->addSql('ALTER INDEX idx_b5820c3e639666d6 RENAME TO idx_meal_recipe_meal');
        $this->addSql('ALTER TABLE participant ALTER id SET DEFAULT nextval(\'participant_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE participant ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE participant ALTER nights_present TYPE JSONB');
        $this->addSql('ALTER INDEX idx_d79f6b11a5bc2e0e RENAME TO idx_participant_trip');
        $this->addSql('ALTER TABLE recipe ALTER id SET DEFAULT nextval(\'recipe_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE recipe ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE recipe_ingredient ALTER id SET DEFAULT nextval(\'recipe_ingredient_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE recipe_ingredient ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE recipe_ingredient ALTER quantity TYPE NUMERIC(10, 2)');
        $this->addSql('ALTER INDEX idx_22d1fe13933fe08c RENAME TO idx_recipe_ingredient_ingredient');
        $this->addSql('ALTER INDEX idx_22d1fe1359d8a214 RENAME TO idx_recipe_ingredient_recipe');
        $this->addSql('ALTER TABLE trip ALTER id SET DEFAULT nextval(\'trip_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE trip ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE trip ALTER total_budget TYPE NUMERIC(10, 2)');
    }
}
