<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260414123601 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE participant DROP arrival_date');
        $this->addSql('ALTER TABLE participant DROP departure_date');
        $this->addSql('ALTER TABLE participant DROP nights_present');
        $this->addSql('ALTER TABLE participant_trip DROP CONSTRAINT fk_a2e2e705a5bc2e0e');
        $this->addSql('ALTER TABLE participant_trip DROP CONSTRAINT fk_a2e2e7059d1c3019');
        $this->addSql('ALTER TABLE participant_trip DROP CONSTRAINT participant_trip_pkey');
        $this->addSql('ALTER TABLE participant_trip ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL');
        $this->addSql('ALTER TABLE participant_trip ADD arrival_date DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE participant_trip ADD departure_date DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE participant_trip ADD nights_present JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE participant_trip ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE participant_trip ADD CONSTRAINT FK_A2E2E705A5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participant_trip ADD CONSTRAINT FK_A2E2E7059D1C3019 FOREIGN KEY (participant_id) REFERENCES participant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participant_trip ADD PRIMARY KEY (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE participant ADD arrival_date DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE participant ADD departure_date DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE participant ADD nights_present JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE participant_trip DROP CONSTRAINT FK_A2E2E7059D1C3019');
        $this->addSql('ALTER TABLE participant_trip DROP CONSTRAINT FK_A2E2E705A5BC2E0E');
        $this->addSql('ALTER TABLE participant_trip DROP CONSTRAINT participant_trip_pkey');
        $this->addSql('ALTER TABLE participant_trip DROP id');
        $this->addSql('ALTER TABLE participant_trip DROP arrival_date');
        $this->addSql('ALTER TABLE participant_trip DROP departure_date');
        $this->addSql('ALTER TABLE participant_trip DROP nights_present');
        $this->addSql('ALTER TABLE participant_trip DROP created_at');
        $this->addSql('ALTER TABLE participant_trip ADD CONSTRAINT fk_a2e2e7059d1c3019 FOREIGN KEY (participant_id) REFERENCES participant (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE participant_trip ADD CONSTRAINT fk_a2e2e705a5bc2e0e FOREIGN KEY (trip_id) REFERENCES trip (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE participant_trip ADD PRIMARY KEY (participant_id, trip_id)');
    }
}
