<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260414183732 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE participant_meal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, participant_id INT NOT NULL, meal_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4A429CA29D1C3019 ON participant_meal (participant_id)');
        $this->addSql('CREATE INDEX IDX_4A429CA2639666D6 ON participant_meal (meal_id)');
        $this->addSql('ALTER TABLE participant_meal ADD CONSTRAINT FK_4A429CA29D1C3019 FOREIGN KEY (participant_id) REFERENCES participant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participant_meal ADD CONSTRAINT FK_4A429CA2639666D6 FOREIGN KEY (meal_id) REFERENCES meal (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE participant_meal DROP CONSTRAINT FK_4A429CA29D1C3019');
        $this->addSql('ALTER TABLE participant_meal DROP CONSTRAINT FK_4A429CA2639666D6');
        $this->addSql('DROP TABLE participant_meal');
    }
}
