/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Ingredient resources.
         * @description Retrieves the collection of Ingredient resources.
         */
        get: operations["api_ingredients_get_collection"];
        put?: never;
        /**
         * Creates a Ingredient resource.
         * @description Creates a Ingredient resource.
         */
        post: operations["api_ingredients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingredients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Ingredient resource.
         * @description Retrieves a Ingredient resource.
         */
        get: operations["api_ingredients_id_get"];
        /**
         * Replaces the Ingredient resource.
         * @description Replaces the Ingredient resource.
         */
        put: operations["api_ingredients_id_put"];
        post?: never;
        /**
         * Removes the Ingredient resource.
         * @description Removes the Ingredient resource.
         */
        delete: operations["api_ingredients_id_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Meal resources.
         * @description Retrieves the collection of Meal resources.
         */
        get: operations["api_meals_get_collection"];
        put?: never;
        /**
         * Creates a Meal resource.
         * @description Creates a Meal resource.
         */
        post: operations["api_meals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Meal resource.
         * @description Retrieves a Meal resource.
         */
        get: operations["api_meals_id_get"];
        /**
         * Replaces the Meal resource.
         * @description Replaces the Meal resource.
         */
        put: operations["api_meals_id_put"];
        post?: never;
        /**
         * Removes the Meal resource.
         * @description Removes the Meal resource.
         */
        delete: operations["api_meals_id_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Participant resources.
         * @description Retrieves the collection of Participant resources.
         */
        get: operations["api_participants_get_collection"];
        put?: never;
        /**
         * Creates a Participant resource.
         * @description Creates a Participant resource.
         */
        post: operations["api_participants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Participant resource.
         * @description Retrieves a Participant resource.
         */
        get: operations["api_participants_id_get"];
        /**
         * Replaces the Participant resource.
         * @description Replaces the Participant resource.
         */
        put: operations["api_participants_id_put"];
        post?: never;
        /**
         * Removes the Participant resource.
         * @description Removes the Participant resource.
         */
        delete: operations["api_participants_id_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participant_meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of ParticipantMeal resources.
         * @description Retrieves the collection of ParticipantMeal resources.
         */
        get: operations["api_participant_meals_get_collection"];
        put?: never;
        /**
         * Creates a ParticipantMeal resource.
         * @description Creates a ParticipantMeal resource.
         */
        post: operations["api_participant_meals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participant_meals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a ParticipantMeal resource.
         * @description Retrieves a ParticipantMeal resource.
         */
        get: operations["api_participant_meals_id_get"];
        /**
         * Replaces the ParticipantMeal resource.
         * @description Replaces the ParticipantMeal resource.
         */
        put: operations["api_participant_meals_id_put"];
        post?: never;
        /**
         * Removes the ParticipantMeal resource.
         * @description Removes the ParticipantMeal resource.
         */
        delete: operations["api_participant_meals_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the ParticipantMeal resource.
         * @description Updates the ParticipantMeal resource.
         */
        patch: operations["api_participant_meals_id_patch"];
        trace?: never;
    };
    "/api/participant_trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of ParticipantTrip resources.
         * @description Retrieves the collection of ParticipantTrip resources.
         */
        get: operations["api_participant_trips_get_collection"];
        put?: never;
        /**
         * Creates a ParticipantTrip resource.
         * @description Creates a ParticipantTrip resource.
         */
        post: operations["api_participant_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participant_trips/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a ParticipantTrip resource.
         * @description Retrieves a ParticipantTrip resource.
         */
        get: operations["api_participant_trips_id_get"];
        /**
         * Replaces the ParticipantTrip resource.
         * @description Replaces the ParticipantTrip resource.
         */
        put: operations["api_participant_trips_id_put"];
        post?: never;
        /**
         * Removes the ParticipantTrip resource.
         * @description Removes the ParticipantTrip resource.
         */
        delete: operations["api_participant_trips_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the ParticipantTrip resource.
         * @description Updates the ParticipantTrip resource.
         */
        patch: operations["api_participant_trips_id_patch"];
        trace?: never;
    };
    "/api/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Recipe resources.
         * @description Retrieves the collection of Recipe resources.
         */
        get: operations["api_recipes_get_collection"];
        put?: never;
        /**
         * Creates a Recipe resource.
         * @description Creates a Recipe resource.
         */
        post: operations["api_recipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Recipe resource.
         * @description Retrieves a Recipe resource.
         */
        get: operations["api_recipes_id_get"];
        /**
         * Replaces the Recipe resource.
         * @description Replaces the Recipe resource.
         */
        put: operations["api_recipes_id_put"];
        post?: never;
        /**
         * Removes the Recipe resource.
         * @description Removes the Recipe resource.
         */
        delete: operations["api_recipes_id_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipe_ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of RecipeIngredient resources.
         * @description Retrieves the collection of RecipeIngredient resources.
         */
        get: operations["api_recipe_ingredients_get_collection"];
        put?: never;
        /**
         * Creates a RecipeIngredient resource.
         * @description Creates a RecipeIngredient resource.
         */
        post: operations["api_recipe_ingredients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipe_ingredients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a RecipeIngredient resource.
         * @description Retrieves a RecipeIngredient resource.
         */
        get: operations["api_recipe_ingredients_id_get"];
        /**
         * Replaces the RecipeIngredient resource.
         * @description Replaces the RecipeIngredient resource.
         */
        put: operations["api_recipe_ingredients_id_put"];
        post?: never;
        /**
         * Removes the RecipeIngredient resource.
         * @description Removes the RecipeIngredient resource.
         */
        delete: operations["api_recipe_ingredients_id_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Trip resources.
         * @description Retrieves the collection of Trip resources.
         */
        get: operations["api_trips_get_collection"];
        put?: never;
        /**
         * Creates a Trip resource.
         * @description Creates a Trip resource.
         */
        post: operations["api_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Trip resource.
         * @description Retrieves a Trip resource.
         */
        get: operations["api_trips_id_get"];
        /**
         * Replaces the Trip resource.
         * @description Replaces the Trip resource.
         */
        put: operations["api_trips_id_put"];
        post?: never;
        /**
         * Removes the Trip resource.
         * @description Removes the Trip resource.
         */
        delete: operations["api_trips_id_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Unprocessable entity */
        ConstraintViolation: {
            /** @default 422 */
            status: number;
            violations?: {
                /** @description The property path of the violation */
                propertyPath: string;
                /** @description The message associated with the violation */
                message: string;
                /** @description The code of the violation */
                code?: string;
                /** @description An extra hint to understand the violation */
                hint?: string;
                /** @description The serialized payload of the violation */
                payload?: {
                    [key: string]: unknown;
                };
            }[];
            readonly detail?: string;
            readonly type?: string;
            readonly title?: string | null;
            readonly instance?: string | null;
        };
        /** @description Unprocessable entity */
        "ConstraintViolation.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @default 422 */
            status: number;
            violations?: {
                /** @description The property path of the violation */
                propertyPath: string;
                /** @description The message associated with the violation */
                message: string;
                /** @description The code of the violation */
                code?: string;
                /** @description An extra hint to understand the violation */
                hint?: string;
                /** @description The serialized payload of the violation */
                payload?: {
                    [key: string]: unknown;
                };
            }[];
            readonly detail?: string;
            readonly description?: string;
            readonly type?: string;
            readonly title?: string | null;
            readonly instance?: string | null;
        };
        /** @description A representation of common errors. */
        Error: {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
        };
        /** @description A representation of common errors. */
        "Error.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
            readonly description?: string | null;
        };
        HydraCollectionBaseSchema: components["schemas"]["HydraCollectionBaseSchemaNoPagination"] & {
            /**
             * @example {
             *       "@id": "string",
             *       "@type": "string",
             *       "first": "string",
             *       "last": "string",
             *       "previous": "string",
             *       "next": "string"
             *     }
             */
            view?: {
                /** Format: iri-reference */
                "@id"?: string;
                "@type"?: string;
                /** Format: iri-reference */
                first?: string;
                /** Format: iri-reference */
                last?: string;
                /** Format: iri-reference */
                previous?: string;
                /** Format: iri-reference */
                next?: string;
            };
        };
        HydraCollectionBaseSchemaNoPagination: {
            totalItems?: number;
            search?: {
                "@type"?: string;
                template?: string;
                variableRepresentation?: string;
                mapping?: {
                    "@type"?: string;
                    variable?: string;
                    property?: string | null;
                    required?: boolean;
                }[];
            };
        };
        HydraItemBaseSchema: {
            "@context"?: string | ({
                "@vocab": string;
                /** @enum {string} */
                hydra: "http://www.w3.org/ns/hydra/core#";
            } & {
                [key: string]: unknown;
            });
            "@id": string;
            "@type": string;
        };
        "Ingredient-ingredient.write": {
            readonly id?: number;
            name?: string;
            defaultUnit?: string | null;
            defaultQuantity?: string | null;
            averagePrice?: string | null;
            category?: string | null;
            notes?: string | null;
        };
        "Ingredient.jsonld-ingredient.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            name?: string;
            defaultUnit?: string | null;
            defaultQuantity?: string | null;
            averagePrice?: string | null;
            category?: string | null;
            notes?: string | null;
            /** Format: date-time */
            readonly createdAt?: string;
            /** @description Calcule le prix par unité de mesure */
            readonly pricePerUnit?: number | null;
        };
        "Ingredient.jsonld-meal.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            name?: string;
            defaultUnit?: string | null;
        };
        "Ingredient.jsonld-recipe.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            name?: string;
            defaultUnit?: string | null;
        };
        "Meal-meal.write": {
            readonly id?: number;
            name?: string;
            mealType?: string;
            /** Format: date-time */
            date?: string;
            description?: string | null;
            estimatedCost?: string | null;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            trip?: string;
            recipes?: string[];
            participants?: string[];
        };
        "Meal.jsonld-meal.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            name?: string;
            mealType?: string;
            /** Format: date-time */
            date?: string;
            description?: string | null;
            estimatedCost?: string | null;
            recipes?: components["schemas"]["Recipe.jsonld-meal.read"][];
            participants?: components["schemas"]["Participant.jsonld-meal.read"][];
            /** Format: date-time */
            readonly createdAt?: string;
            participantMeals?: components["schemas"]["ParticipantMeal.jsonld-meal.read"][];
            readonly numberOfPortions?: number;
            /** @description Calcule le coût par portion pour ce repas */
            readonly costPerPortion?: number | null;
            /** @description Récupère tous les ingrédients nécessaires pour ce repas */
            readonly allIngredients?: {
                [key: string]: {
                    [key: string]: number | string;
                };
            };
        };
        "Meal.jsonld-trip.read_global.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            name?: string;
            mealType?: string;
            /** Format: date-time */
            date?: string;
            recipes?: string[];
        };
        "Participant-participant.write": {
            readonly id?: number;
            name?: string;
            email?: string | null;
        };
        "Participant.jsonld-meal.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            name?: string;
        };
        "Participant.jsonld-participant.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            name?: string;
            email?: string | null;
            /** Format: date-time */
            readonly createdAt?: string;
        };
        "Participant.jsonld-trip.read_global.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            name?: string;
            email?: string | null;
        };
        "ParticipantMeal-participantMeal.write": {
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            participant?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            meal?: string;
        };
        "ParticipantMeal-participantMeal.write.jsonMergePatch": {
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            participant?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            meal?: string;
        };
        "ParticipantMeal.jsonld-meal.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            participant?: components["schemas"]["Participant.jsonld-meal.read"];
        };
        "ParticipantMeal.jsonld-participantMeal.read_global.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            participant?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            meal?: string;
            /** Format: date-time */
            readonly createdAt?: string;
        };
        "ParticipantTrip-participantTrip.write": {
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            participant?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            trip?: string;
            nightsPresent?: string[] | null;
        };
        "ParticipantTrip-participantTrip.write.jsonMergePatch": {
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            participant?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            trip?: string;
            nightsPresent?: string[] | null;
        };
        "ParticipantTrip.jsonld-participantTrip.read_global.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            participant?: string;
            trip?: components["schemas"]["Trip.jsonld-participantTrip.read_global.read"];
            nightsPresent?: string[] | null;
            /** Format: date-time */
            readonly createdAt?: string;
            /** @description Compte le nombre de nuits où le participant est présent */
            readonly nightsCount?: number;
        };
        "ParticipantTrip.jsonld-trip.read_global.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            participant?: components["schemas"]["Participant.jsonld-trip.read_global.read"];
            nightsPresent?: string[] | null;
            /** Format: date-time */
            readonly createdAt?: string;
            /** @description Compte le nombre de nuits où le participant est présent */
            readonly nightsCount?: number;
        };
        "Recipe-recipe.write": {
            readonly id?: number;
            name?: string;
            description?: string | null;
            defaultPortions?: number;
            instructions?: string | null;
            estimatedCost?: string | null;
            recipeIngredients?: components["schemas"]["RecipeIngredient-recipe.write"][];
        };
        "Recipe.jsonld-meal.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            name?: string;
            defaultPortions?: number;
            recipeIngredients?: components["schemas"]["RecipeIngredient.jsonld-meal.read"][];
        };
        "Recipe.jsonld-recipe.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            name?: string;
            description?: string | null;
            defaultPortions?: number;
            instructions?: string | null;
            estimatedCost?: string | null;
            /** Format: date-time */
            readonly createdAt?: string;
            recipeIngredients?: components["schemas"]["RecipeIngredient.jsonld-recipe.read"][];
            /** @description Calcule le coût par portion de la recette */
            readonly costPerPortion?: number | null;
        };
        "RecipeIngredient-recipe.write": {
            readonly id?: number;
            quantity?: number;
            unit?: string | null;
            preparationNotes?: string | null;
            recipe?: components["schemas"]["Recipe-recipe.write"];
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            ingredient?: string;
        };
        "RecipeIngredient.jsonld-meal.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            quantity?: number;
            unit?: string | null;
            ingredient?: components["schemas"]["Ingredient.jsonld-meal.read"];
        };
        "RecipeIngredient.jsonld-recipe.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            quantity?: number;
            unit?: string | null;
            preparationNotes?: string | null;
            ingredient?: components["schemas"]["Ingredient.jsonld-recipe.read"];
        };
        "Trip-trip.create": {
            readonly id?: number;
            name?: string;
            /** @default 1 */
            nights: number;
            /** @default 0 */
            cottageCost: number;
            /** Format: date-time */
            startDate?: string;
            description?: string | null;
        };
        "Trip-trip.update": {
            readonly id?: number;
            name?: string;
            /** @default 1 */
            nights: number;
            /** @default 0 */
            cottageCost: number;
            /** Format: date-time */
            startDate?: string;
            description?: string | null;
        };
        "Trip.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            name?: string;
            /** @default 1 */
            nights: number;
            /** @default 0 */
            cottageCost: number;
            /** Format: date-time */
            startDate?: string;
            description?: string | null;
            /** Format: date-time */
            readonly createdAt?: string;
            participantTrips?: string[];
            meals?: string[];
            /** @description Calcule le coût par nuitée */
            readonly costPerNight?: number | null;
            /** @description Calcule le coût total pour chaque participant */
            readonly participantsCosts?: {
                [key: string]: number;
            };
        };
        "Trip.jsonld-participantTrip.read_global.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            name?: string;
            /** @default 1 */
            nights: number;
            /** @default 0 */
            cottageCost: number;
            /** Format: date-time */
            startDate?: string;
            description?: string | null;
            /** Format: date-time */
            readonly createdAt?: string;
        };
        "Trip.jsonld-trip.read_global.read": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            name?: string;
            /** @default 1 */
            nights: number;
            /** @default 0 */
            cottageCost: number;
            /** Format: date-time */
            startDate?: string;
            description?: string | null;
            /** Format: date-time */
            readonly createdAt?: string;
            participantTrips?: components["schemas"]["ParticipantTrip.jsonld-trip.read_global.read"][];
            meals?: components["schemas"]["Meal.jsonld-trip.read_global.read"][];
            /** @description Calcule le coût par nuitée */
            readonly costPerNight?: number | null;
            /** @description Calcule le coût total pour chaque participant */
            readonly participantsCosts?: {
                [key: string]: number;
            };
        };
        "Trip.jsonld-trip.readcollection_global.readcollection": components["schemas"]["HydraItemBaseSchema"] & {
            readonly id?: number;
            name?: string;
            /** @default 1 */
            nights: number;
            /** @default 0 */
            cottageCost: number;
            /** Format: date-time */
            startDate?: string;
            description?: string | null;
            /** Format: date-time */
            readonly createdAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_ingredients_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                name?: string;
                category?: string;
                "category[]"?: string[];
                "order[name]"?: "asc" | "desc";
                "order[category]"?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingredient collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Ingredient.jsonld-ingredient.read"][];
                    };
                };
            };
        };
    };
    api_ingredients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Ingredient resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Ingredient-ingredient.write"];
            };
        };
        responses: {
            /** @description Ingredient resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Ingredient.jsonld-ingredient.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_ingredients_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ingredient identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingredient resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Ingredient.jsonld-ingredient.read"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_ingredients_id_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ingredient identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Ingredient resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Ingredient-ingredient.write"];
            };
        };
        responses: {
            /** @description Ingredient resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Ingredient.jsonld-ingredient.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_ingredients_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ingredient identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingredient resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_meals_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                trip?: string;
                "trip[]"?: string[];
                mealType?: string;
                "mealType[]"?: string[];
                "order[date]"?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meal collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Meal.jsonld-meal.read"][];
                    };
                };
            };
        };
    };
    api_meals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Meal resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Meal-meal.write"];
            };
        };
        responses: {
            /** @description Meal resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Meal.jsonld-meal.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_meals_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Meal identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meal resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Meal.jsonld-meal.read"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_meals_id_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Meal identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Meal resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Meal-meal.write"];
            };
        };
        responses: {
            /** @description Meal resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Meal.jsonld-meal.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_meals_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Meal identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meal resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_participants_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Participant collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Participant.jsonld-participant.read"][];
                    };
                };
            };
        };
    };
    api_participants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Participant resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Participant-participant.write"];
            };
        };
        responses: {
            /** @description Participant resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Participant.jsonld-participant.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_participants_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Participant identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Participant resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Participant.jsonld-participant.read"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_participants_id_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Participant identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Participant resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Participant-participant.write"];
            };
        };
        responses: {
            /** @description Participant resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Participant.jsonld-participant.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_participants_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Participant identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Participant resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_participant_meals_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                participant?: string;
                "participant[]"?: string[];
                meal?: string;
                "meal[]"?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ParticipantMeal collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["ParticipantMeal.jsonld-participantMeal.read_global.read"][];
                    };
                };
            };
        };
    };
    api_participant_meals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new ParticipantMeal resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["ParticipantMeal-participantMeal.write"];
            };
        };
        responses: {
            /** @description ParticipantMeal resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ParticipantMeal.jsonld-participantMeal.read_global.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_participant_meals_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ParticipantMeal identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ParticipantMeal resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ParticipantMeal.jsonld-participantMeal.read_global.read"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_participant_meals_id_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ParticipantMeal identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated ParticipantMeal resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["ParticipantMeal-participantMeal.write"];
            };
        };
        responses: {
            /** @description ParticipantMeal resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ParticipantMeal.jsonld-participantMeal.read_global.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_participant_meals_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ParticipantMeal identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ParticipantMeal resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_participant_meals_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ParticipantMeal identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated ParticipantMeal resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["ParticipantMeal-participantMeal.write.jsonMergePatch"];
            };
        };
        responses: {
            /** @description ParticipantMeal resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ParticipantMeal.jsonld-participantMeal.read_global.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_participant_trips_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                participant?: string;
                "participant[]"?: string[];
                trip?: string;
                "trip[]"?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ParticipantTrip collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["ParticipantTrip.jsonld-participantTrip.read_global.read"][];
                    };
                };
            };
        };
    };
    api_participant_trips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new ParticipantTrip resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["ParticipantTrip-participantTrip.write"];
            };
        };
        responses: {
            /** @description ParticipantTrip resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ParticipantTrip.jsonld-participantTrip.read_global.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_participant_trips_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ParticipantTrip identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ParticipantTrip resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ParticipantTrip.jsonld-participantTrip.read_global.read"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_participant_trips_id_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ParticipantTrip identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated ParticipantTrip resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["ParticipantTrip-participantTrip.write"];
            };
        };
        responses: {
            /** @description ParticipantTrip resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ParticipantTrip.jsonld-participantTrip.read_global.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_participant_trips_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ParticipantTrip identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ParticipantTrip resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_participant_trips_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ParticipantTrip identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated ParticipantTrip resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["ParticipantTrip-participantTrip.write.jsonMergePatch"];
            };
        };
        responses: {
            /** @description ParticipantTrip resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ParticipantTrip.jsonld-participantTrip.read_global.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_recipes_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                name?: string;
                "order[name]"?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recipe collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Recipe.jsonld-recipe.read"][];
                    };
                };
            };
        };
    };
    api_recipes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Recipe resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Recipe-recipe.write"];
            };
        };
        responses: {
            /** @description Recipe resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Recipe.jsonld-recipe.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_recipes_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Recipe identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recipe resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Recipe.jsonld-recipe.read"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_recipes_id_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Recipe identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Recipe resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Recipe-recipe.write"];
            };
        };
        responses: {
            /** @description Recipe resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Recipe.jsonld-recipe.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_recipes_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Recipe identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recipe resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_recipe_ingredients_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                recipe?: string;
                "recipe[]"?: string[];
                ingredient?: string;
                "ingredient[]"?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RecipeIngredient collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["RecipeIngredient.jsonld-recipe.read"][];
                    };
                };
            };
        };
    };
    api_recipe_ingredients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new RecipeIngredient resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["RecipeIngredient-recipe.write"];
            };
        };
        responses: {
            /** @description RecipeIngredient resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["RecipeIngredient.jsonld-recipe.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_recipe_ingredients_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description RecipeIngredient identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RecipeIngredient resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["RecipeIngredient.jsonld-recipe.read"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_recipe_ingredients_id_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description RecipeIngredient identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated RecipeIngredient resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["RecipeIngredient-recipe.write"];
            };
        };
        responses: {
            /** @description RecipeIngredient resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["RecipeIngredient.jsonld-recipe.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_recipe_ingredients_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description RecipeIngredient identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RecipeIngredient resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_trips_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                name?: string;
                "order[startDate]"?: "asc" | "desc";
                "order[name]"?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Trip.jsonld-trip.readcollection_global.readcollection"][];
                    };
                };
            };
        };
    };
    api_trips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Trip resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Trip-trip.create"];
            };
        };
        responses: {
            /** @description Trip resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Trip.jsonld-trip.read_global.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_trips_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Trip.jsonld-trip.read_global.read"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_trips_id_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Trip resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Trip-trip.update"];
            };
        };
        responses: {
            /** @description Trip resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Trip.jsonld-trip.read_global.read"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_trips_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
